aliyun:
  accessKey: LTAI5tGJ3yGFbfkVuXLiUPvD
  accessKeySecret: CDHFt9a1kMmOB42m9ke8nP3Xq8e5lA

server:
  port: 8204
spring:
  application:
    name: service-msm
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 192.168.91.128
    password: 123456
  cloud:
    nacos:
      server-addr: 192.168.91.128:8848


feign:
  client:
    config:
      default:   #配置全局的feign的调用超时时间  如果 有指定的服务配置 默认的配置不会生效
        connectTimeout: 30000 # 指定的是 消费者 连接服务提供者的连接超时时间 是否能连接  单位是毫秒
        readTimeout: 50000  # 指定的是调用服务提供者的 服务 的超时时间（）  单位是毫秒




