server:
  port: 8201

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

spring:
  application:
    name: service-hosp
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.91.128:3306/yygh_hosp?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: GuliHikariPool
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 192.168.91.128
    password: 123456
  data:
    mongodb:
      uri: mongodb://192.168.91.128:27017/yygh_hosp
  cloud:
    nacos:
      server-addr: 192.168.91.128:8848

  rabbitmq:
    host: 192.168.91.128
    port: 5672
    username: guest
    password: guest
feign:
  client:
    config:
      default:   #配置全局的feign的调用超时时间  如果 有指定的服务配置 默认的配置不会生效
        connectTimeout: 30000 # 指定的是 消费者 连接服务提供者的连接超时时间 是否能连接  单位是毫秒
        readTimeout: 50000  # 指定的是调用服务提供者的 服务 的超时时间（）  单位是毫秒


#  data:
#    mongodb:
##      注意这种方式不能连接, 坑死--------------------------死坑死坑,mongo设置了也不需要配置用户名密码
#                         yml格式不合适换成properties
#      host: 192.168.91.128
#      port: 27017
##      database: yygh_hosps #指定操作的数据库
#      username: root
#      password: 123455
#      authentication-database: admin
#      uri: mongodb://admin:admin@192.168.91.128:27017



#  main:
#    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
#    cloud:
#      sentinel:
#        transport:
#          dashboard: http://192.168.91.128:8858

#


#feign:
#  sentinel:
#    enabled: true
#  client:
#    config:
#      default:   #配置全局的feign的调用超时时间  如果 有指定的服务配置 默认的配置不会生效
#        connectTimeout: 30000 # 指定的是 消费者 连接服务提供者的连接超时时间 是否能连接  单位是毫秒
#        readTimeout: 50000  # 指定的是调用服务提供者的 服务 的超时时间（）  单位是毫秒