server:
  port: 8207

spring:
  application:
    name: service-task
  redis:
    host: 192.168.91.128
    password: 123456
  cloud:
    nacos:
      server-addr: 192.168.91.128:8848

  rabbitmq:
    host: 192.168.91.128
    port: 5672
    username: admin
    password: admin
